spring.application.name=lin-spring-elasticsearch
server.port=8080

# Elasticsearch configuration
spring.elasticsearch.uris=http://localhost:9200

# Logging
logging.level.org.springframework.data.elasticsearch=DEBUG
