spring:
  application:
    name: lin-spring-micrometer

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0  # 100% tracing
  otlp:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans