spring.application.name=lin-spring-outbox

spring.datasource.url=jdbc:h2:mem:outboxdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# 轮询 Outbox 间隔（毫秒）
app.outbox.relay.fixed-delay-ms=2000
app.outbox.relay.batch-size=20
app.outbox.relay.max-retries=3

logging.level.com.lin.spring.outbox=INFO
