### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### 在 URL 本身中包含版本
GET http://localhost:8081/orders HTTP/1.1

### ab -n 10 -c 2 http://localhost:8081/orders