apiVersion: apps/v1
kind: Deployment
metadata:
  name: lin-spring-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lin-spring-k8s
  template:
    metadata:
      labels:
        app: lin-spring-k8s
    spec:
      containers:
      - name: lin-spring-k8s-app
        image: lin-spring-k8s-app:latest
        imagePullPolicy: IfNotPresent  # Never  强制使用本地镜像，不拉取
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lin-spring-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: lin-spring-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

